image: docker:latest

stages:
  - Build image
  - Test acceptation

build:
  # Official docker image.
  stage: Build image
  script:
    - docker build -t alpinehelloworld .


test acceptation:
  # Official docker image.
  stage: Test acceptation
  script:
    - docker run -d -p 80:5000 --env PORT=5000 --name webapp alpinehelloworld
    - sleep 5
    - apk --no-cache add curl
    - curl "http://localhost" | grep -q "Hello world!"

