image: docker:latest
services:
  - name: docker:dind
    alias: docker

stages:
  - Build image
  - Test acceptation

build:
  # Official docker image.
  stage: Build image
  script:
    - docker build -t alpinehelloworld .


test acceptation:
  # Official docker image.
  stage: Test acceptation
  script:
    - docker run -d -p 80:5000 -e PORT=5000 --name webapp alpinehelloworld
    - sleep 5
    - apk --no-cache add curl
    - curl "http://docker" | grep -q "Hello world!"

