stages:
  - Build image
  - Test acceptation

build:
  # Official docker image.
  image: docker:latest
  stage: Build image
  services:
    - docker:dind
  script:
    - docker build -t alpinehelloworld .
    - docker save alpinehelloworld > alpinehelloworld.tar
  artifacts:
    paths:
      - alpinehelloworld.tar


test acceptation:
  # Official docker image.
  image: docker:latest
  stage: Test acceptation
  services:
    - docker:dind
  script:
    - docker load < alpinehelloworld.tar
    - docker run -d -p 80:80 -e PORT=80 --name webapp alpinehelloworld
    - sleep 5
    - apk --no-cache add curl
    - docker ps -a
    - docker logs webapp
    - curl "http://localhost" | grep -q "Hello world!"

